version: "3.4"
services:
  node:
    stdin_open: true
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "80:8080"
    volumes:
      - .:/app
      - node_modules:/app/node_modules

volumes:
  node_modules:
    driver: local
